---
- name: run tasks n all hosts
  hosts: "*"
  tasks: 
   - name: run command with shell
     shell: echo "Hello, shell!" > /tmp/shell_output

- name: run command with command
  command: echo "Hello, command!" > /tmp/command_output